version: 2

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/clojure:lein-2.9.6
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: lein-deps-{{ checksum "project.clj" }}
      - run: lein deps
      - run: lein do fetch --no-db --no-card-images, eftest
      - save_cache:
          paths:
            - ~/.m2
            - ~/.lein
          key: lein-deps-{{ checksum "project.clj" }}
